#===================================================================================================
# Copyright © 2018 nanorep.
# NanorepUI SDK.
# All rights reserved.
#===================================================================================================

platform :ios, "9.0"
use_frameworks!

install! 'cocoapods',
         :deterministic_uuids => false

# Dev
source 'https://github.com/nanorepsdk/NRSDK-Dev-specs.git'
# Production
# source 'https://github.com/nanorepsdk/NRSDK-specs.git'

source 'https://github.com/CocoaPods/Specs'

target 'BasicSample' do
    pod 'OpalImagePicker'
    pod 'Bold360AI' , '3.6.16'
end
